---
version: 2
multicolumn: false
web-width: '1500'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/PBConnections/SubDiagrams.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/PBConnections"
    url: "/users/14026/articles/155729/master/file/figures/PBConnections/SubDiagrams.svg"
