---
version: 2
multicolumn: 
web-width: 800
export-width: 
align: 
float: 
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ResponseCharac/FigureResponses.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/ResponseCharac"
    url: "/users/14026/articles/155729/master/file/figures/ResponseCharac/FigureResponses.svg"
